name: produitapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Flutter lints version is aligned with Flutter's SDK version

flutter:
  uses-material-design: true
